##### Alexander Ricky Putra Pangestu
##### NIM : 255314035
##### Tanggal : 3 September 2026

### 1. Membuat List

In [2]:
#1.2. Buatlah sebuah list dengan nama "mylist" berisi "0",1,"two", 2,3,4
mylist =(["0",1,"two",2,3,4])

#1.3. Tampilkan isi mylist
print(mylist)

#1.4. Apakah terjadi error ?
# tidak error

# 1.5. Mengapa ?
# karena list data dapat menyimpan berbagai jenis data

['0', 1, 'two', 2, 3, 4]
0
1
two
2
3
4
2


### 2. Mencetak isi list

In [ ]:
#2.1. Tampilkan setiap element dari mylist
for item in mylist:
    print(item)

#2.2. Tampilkan isi mylist index ke-3 
print (mylist[3])

### 3. Membuat Array dari NumPy

In [3]:
#3.0. Kesepakatan programmer Pyhton, Numpy biasanya disingkat np. Selanjutnya gunakan np
## import numpy as np

import numpy as np

#3.1. Ubahlah  mylist kedalam numpy array beri nama myarray
myarray = np.array([mylist])

#3.2. Tampilkan isi myarray
print(myarray)

#3.3. Buatlah array menggunakan numpy array berisi nilai : 10,11,12,13,14 beri nama myarray2
myarray2 = ([10,11,12,13,14])

#3.4. Tampilkan isi setiap elemen dari myarray2. Tampilan yang diinginkan : [10 11 12 13 14]
print (myarray2)

#3.5. Tampilkan isi myarray2 lagi, tampilan yang diinginkan : Tampilan yang diinginkan 
#(tanpa # tidak ditampilkan)
 #      myarray[0]=10
  #     myarray[1]=11
   #    myarray[2]=12
    #   myarray[3]=13
     #  myarray[4]=14
indeks = 0
for a in myarray2:
    print(f"myarray[{indeks}] = {a}")
    indeks +=1


#3.6. Tampilkan elemen dari myarray2 index ke-3 yaitu (13).
print(myarray2[3])

[['0' '1' 'two' '2' '3' '4']]
[10, 11, 12, 13, 14]
myarray[0] = 10
myarray[1] = 11
myarray[2] = 12
myarray[3] = 13
myarray[4] = 14
13


### 4. Perkalian list dan array numpy

In [23]:
# 4.1. Buatlah sebuah list dengan nama mylist2 berisi 10,11,12,13,14
mylist2 = np.array ([10,11,12,13,14])

# 4.2. Kalikan mylist2 dengan 3  
print (mylist2 * 3)
# 4.3. Kalikan myarray2 dengan 3 (myarray2 ada pada bagian 3.3)
print (myarray2 * 3)

# 4.4. Apa perbedaan anatara 4.2 dan 4.3. Jelaskan secara singkat
# kalo 4.2, itu mengalikasi ke tiap data dengan kali 3 sehingga menghasilkan jumlah perkalian, 
# kalo 4.3, itu elemen yang ada di list di kalikan sebanyak 3 kali sehingga ada 3 data list baru

[30 33 36 39 42]
[10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14]


### 5. Membuat array dengan fungsi lain

In [41]:
#5.1. buatlah array yang berisi nilai 0 (gunakan fungsi zeros) 
### sebanyak 7 beri nama arrayzeros, tampilkan hasilnya
arrayzeros = np.zeros (7)
print (arrayzeros)

#5.2. buatlah array yang berisi nilai 1 (gunakan fungsi ones) 
### sebanyak 7 beri nama arrayones, tampilkan hasilnya
arrayones = np.ones (7)
print (arrayones)

#5.3. buatlah array dimulai dari 10 sd 50 step 5 (gunakan fungsi arange) 
### beri nama arrayarange tampilkan hasilnya
arrayarange = np.arange(10,50,5)
print(arrayarange)

#5.4. buatlah array dimulai dari 10 sd 101 step 10 (gunakan fungsi arange) 
### beri nama arrayarange tampilkan hasilnya
arrayarange = np.arange(10,101,10)
print(arrayarange)

#5.5. buatlah array dimulai dari 10 sd 100 sejumlah 10 (gunakan fungsi linspace) 
### beri nama arrayalinspace tampilkan hasilnya
arrayalinspace = np.arange(10,100,10)
print(arrayalinspace)

#5.6. Berikan penjelasan perbedaan antara 5.4 dan 5.5.
# kalo 5.4 membuat range dari 10 sampai dengan 101 dengan step/kelipatan 10 sehingga tercetak 10 dengan kelipatan 10 hingga 100 
# kalo 5.5 membuat range dari 10 sampai dengan 100 dengan step yang sama hanya akan berhenti di 90 karena 100 tidak tercetak 

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[10 15 20 25 30 35 40 45]
[ 10  20  30  40  50  60  70  80  90 100]
[10 20 30 40 50 60 70 80 90]


### 6. Type dari NumPy

In [48]:
# 6.1. Tampilkan tipe dari myarray2
print(type(myarray2))

# 6.2. Tampilkan tipe dari data yang ada dalam myarray2
for a in myarray2:
    print(type(a))

# 6.3. Apa perbedaan antara 6.1 dan 6.2
# kalo 6.1 adalah tipe dari variabel array tersebut
# kalo 6.2 adalah tipe dari dalam data pada array tersebut

<class 'list'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


 ### 7. Multidimensional Array

In [6]:
#7.1. Buatlah array 2 dimensi, beri nama arrku. Isi arrku adalah :
## baris 1 : [11,12,13,14,15], baris 2 =[21,22,23,24,25], baris 3 =[31, 32, 33,34,35]
arrku = np.array([[11,12,13,14,15] ,[21,22,23,24,25] , [31, 32, 33,34,35]])


#7.2. Tampilkan arrku
print (arrku)

#7.3. Tampilkan jumlah elemen dari arrku (size)
print(arrku.size)

#7.4. Tampilkan  dimensi dari arrku (ndim)
print(arrku.ndim)

#7.5. Tampilkan ukuran dari arrku (shape)  
print(arrku.shape)

#7.6. Tampilkan transpose dari arrku (T)
print(arrku.T)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]]
15
2
(3, 5)
[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]
 [15 25 35]]


### 8. Indexing dan Slicing Array

In [32]:
# 8.1. Tampilkan element arrku dari baris kedua dan kolom kelima (hasil : 25)
print(arrku[1,4])

# 8.2. Tampilkan element arrku dari tiga kolom pertama dari baris pertama ([11 12 13])
print(arrku[0,0:3])

# 8.3. Tampilkan element arrku dari baris pertama dan kedua dan kolom ketiga ([13,23])
print(arrku[0: 2,2])

# 8.4. Tampilkan element arrku dari baris pertama dan kedua ([[11, 12, 13, 14, 15],[21, 22, 23, 24, 25]])
print(arrku[0:2,])

# 8.4. Perintah untuk menghasilkan element arrku dari kolom kelima seperti berikut (abaikan ##): 
## array([15],
##       [25],
##       [35])
print(arrku[0:3,4])

25
[11 12 13]
[13 23]
[[11 12 13 14 15]
 [21 22 23 24 25]]
[15 25 35]


### 9. Operasi Aritmatika dan Statistik

In [52]:
#9.1. Buatlah : arr_A = np.array([11,12,13,14,15])
arr_A = np.array([11,12,13,14,15])

#9.2. Buatlah : arr_B = np.array([2,2,2,2,2])
arr_B = np.array([2,2,2,2,2])

#9.3. Lakukan operasi penjualan arry_A dan arry_B. Hasil yang diinginkan
#Penjumlahan =  [13 14 15 16 17]
print(arr_A + arr_B)

#9.4. Lakukan operasi pengurangan arry_A dan arry_B. Hasil yang diinginkan
#Pengurangan =  [9 10 11 12 13]
print(arr_A - arr_B)

#9.5. Lakukan operasi perkalian arry_A dan arry_B. Hasil yang diinginkan
#Perkalian =  [22 24 26 28 30]
print(arr_A * arr_B)

#9.6. Lakukan operasi pembagian arry_A dan arry_B. Hasil yang diinginkan
#Pembagian =  [5.5 6.  6.5 7.  7.5]
print(arr_A / arr_B)

#9.7. Lakukan operasi perpangkatan : arry_A dipangkatkan arry_B. Hasil yang diinginkan
#Perpangkatan =  [121 144 169 196 225]
print(arr_A ** arr_B)

#9.8. Lakukan operasi perkalian dot product arry_A dan arry_B. Hasil yang diinginkan
#Perkalian Dot =  130
print(np.dot(arr_A, arr_B))

#9.9. Tampilkan / cetak isi dari arrku, hasil yang diinginkan (abaikan #)
#[[11 12 13 14 15]
# [21 22 23 24 25]
# [31 32 33 34 35]]
print(arrku[0:3,])


#9.10 tampilkan nilai minimum dari arrku
mini = np.min(arrku)
print(mini)

#9.11 tampilkan nilai maksimum dari arrku
maks = np.max(arrku)
print(maks)

#9.12 tampilkan nilai rata-rata dari arrku
rata = np.mean(arrku)
print(rata)

#9.13 tampilkan nilai total dari arrku
total = np.sum(arrku)
print(total)

#9.14 tampilkan nilai standar deviasi dari arrku
standar = np.std(arrku)
print(standar)

#9.15 tampilkan index nilai minimum
print(arrku.argmin())

#9.16 tampilkan index nilai maksimum
print(arrku.argmax())

## Hasil yang diinginkan dari 9.10 sd 9.16 adalah (abaikan #)

#Nilai minimal =  11
#Nilai maksimal =  35
#Nilai rata-rata =  23.0
#Total nilai =  345
#Standar Deviasi =  8.286535263104035
#Index nilai minimum =  0
#Index nilai maksimum = 14

[13 14 15 16 17]
[ 9 10 11 12 13]
[22 24 26 28 30]
[5.5 6.  6.5 7.  7.5]
[121 144 169 196 225]
130
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]]
11
35
23.0
345
8.286535263104035
0
14


### 10. Reshaping Array

In [65]:
## 10.1 Buatlah array : arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

## 10.2. Ubah arr dengan ukuran 4x3 
#[[ 1  2  3]
# [ 4  5  6]
# [ 7  8  9]
# [10 11 12]]
arr1 = arr.reshape(4,3)
print(arr1)

## 10.3. Lakukan reshape arr menjadi array 3 dimensi 

##[[[ 1  2]
#  [ 3  4]
#  [ 5  6]]

##[[ 7  8]
#  [ 9 10]
#  [11 12]]]
arr2 = arr.reshape(2,3,2)
print(arr2)

## 10.4. Lakukan reshape dengan ukuran array diserahkan kepada python
#[[[ 1  2  3]
#  [ 4  5  6]]

# [[ 7  8  9]
#  [10 11 12]]]
arr3= arr.reshape(2,2,3)
print(arr3)
## 10.5 Lakukan proses flattening array dari arrku
#[11 12 13 14 15 21 22 23 24 25 31 32 33 34 35]
arrflat = arr.flatten()
print(arrflat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
